node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build UI') {
        docker.image('docker.registry/node:8-alpine').inside('-v $HOME/.npmrc:/root/.npmrc') {
            sh 'npm install'
            sh 'npm run build'
        }
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("docker.registry/uaas-ui")
    }

    stage('Push image') {
        /* Finally, we'll push the image into Docker Hub */

        docker.withRegistry('http://docker.registry', 'docker-registry-credentials') {
            app.push("latest")
        }
    }
}